### PR TITLE
Decrypt payloads, invalid hash fix

### LINKED ISSUE #12: Add support for decrypting encrypted features
There are test cases for this in version 0.4.1. See [the latest test cases file](https://github.com/growthbook/growthbook/blob/main/packages/sdk-js/test/cases.json).

### PR DESCRIPTION
**Pull request by tinahollygb**
Adds support for working with encrypted payloads.

Also fixes the invalid hash bug by returning and handling a nil hash.

I've also renamed the `#hash` method to `#get_hash` to avoid conflicts with tooling that uses RBS for typed Ruby (e.g. RubyMine) as it will show warnings that an invalid type is returned for the definition `def hash: () -> Integer`. 

Closes #12 

Documentation is added in this PR: https://github.com/growthbook/growthbook/pull/1221

### CODE REVIEW

File: lib/growthbook/context.rb [hunk 1]
```diff
@@ -34,14 +34,19 @@ def initialize(options = {})
...
-        case key.to_sym
+      options.transform_keys(&:to_sym).each do |key, value|
+        case key
         when :enabled
           @enabled = value
         when :attributes
           self.attributes = value
         when :url
           @url = value
+        when :encryption_key
```
Comment (jdorn) [inline lib/growthbook/context.rb:45]: I prefer calling this `decryption_key` since it's used to decrypt an already encrypted payload.

File: lib/growthbook/util.rb [hunk 2]
```diff
@@ -1,8 +1,10 @@
 # frozen_string_literal: true
 
+require 'base64'
 require 'fnv'
 require 'bigdecimal'
 require 'bigdecimal/util'
+require 'openssl'
```
Comment (jdorn) [inline lib/growthbook/util.rb:7]: Are openssl and base64 required here?  Or should these be moved to the decryption_util file?

**Review by jdorn — APPROVED** [review]
